### ISSUE TITLE
Show more output in the console

### ISSUE THREAD

**Issue by nathaneastwood** [nathaneastwood/brew-ds#6]
Currently it looks as though the script is hanging when it is doing long installations. We need to show more output in the console.

**Comment by raisedbyfinches** [comment]
Getting there, for some reason my \r in the verbose mode [commit](https://github.com/nathaneastwood/brew-ds/commit/8da0660117ad3dfdc39c857d5e2da2d4151b3ea4) doesn't work. It prints all of the  "% complete" text on new lines when it is meant to go back and overwrite the previous line.

**Comment by raisedbyfinches** [comment]
This should be fixed in [8274a67](https://github.com/nathaneastwood/brew-ds/commit/8274a67f022abf623aaf176985413bf2c5878850). Needs testing.

**Comment by raisedbyfinches** [comment]
Fixed.
